Added basic implementation for configuration backups (CS-191)
WildGums/Orchestra pull request #526
Opened 2021-06-03 12:37 UTC by Averus-a

### Description of Change ###
This feature add simple backup for configuration files. It's known issue in certain cases configuration can reset when multiple instances of shell launched. This one implementation allows at least keep and turn back user information.

The default value for number of store backups is **5**
The service do own work before shell shown.
### Issues Resolved ### 

- fixes CS-191 (related)

### API Changes ###

 
Orchestra.Core

### Platforms Affected ### 

- All

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

2021-06-03 13:11 UTC, Averus-a commented
Question: Do we have any other approach to obtain real configuration file paths (E.g. they can be overridden in the ConfigurationService's decendant classes) without using reflection (they are private fields)?

2021-06-03 14:36 UTC, GeertvanHorrik requested changes
1. Please add unit tests (it's ok to write unit test project configuration files to disk)
2. Run unit test for API changes

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Shell.Shared/Services/ShellService.cs
> +            await _configurationBackupService.BackupAsync();
Please move to https://github.com/WildGums/Orchestra/blob/4a4fe3f4502515e8cf08f37cc88b92f950bf97da/src/Orchestra.Shell.Shared/Services/ShellService.cs#L164.

This way we can do it before the user potentially resets the config.

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/Interfaces/IConfigurationBackupService.cs
> +        void Backup();
Do we really need the non-async one?

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +        public void Backup()
make it virtual

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +                    Log.Info($"Configuration file not found on path {roamingConfigFilePath}, skipping backup");
Make it debug, and move it to BackupConfiguration since we repeat ourselves here.

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +                Log.Error(ex, "Failed to create database backup");
database backup?

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +        private readonly IConfigurationService _configurationService;
newline between static / non-static

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            Log.Info($"Creating configuration backup, {applicationDataTarget}");
if (!_fileService.Exists)
{
    Log.Debug(....)
    return;
}

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            var configBackupFolderPath = Path.Combine(_appDataService.GetApplicationDataDirectory(Catel.IO.ApplicationDataTarget.UserRoaming), "backup\\config\\");
always use path.combine

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            if (!_directoryService.Exists(configBackupFolderPath))
Just call DirectoryService.Create, it already checks for existence

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +        private void BackupConfiguration(string configurationFilePath, Catel.IO.ApplicationDataTarget applicationDataTarget)
make protected virtual async

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            var backupConfigurationFiles = _directoryService.GetFiles(configBackupFolderPath, "configuration*").OrderBy(f => f).ToList();
This doesn't check / respect the app data target, so will only allow 2 / 3 backups at a time with a default of 5 items.

Either add the appdata target to the *filename* or as a directory.

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +        public int NumberOfBackups { get; protected set; } = 5;
default to 10

2021-06-03 14:36 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            Log.Info($"Created configration backup, {applicationDataTarget}");
typo

2021-06-03 14:36 UTC, GeertvanHorrik commented
> Question: Do we have any other approach to obtain real configuration file paths (E.g. they can be overridden in the ConfigurationService's decendant classes) without using reflection (they are private fields)?

Unfortunately not.

2021-06-03 18:02 UTC, Averus-a commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            var backupConfigurationFiles = _directoryService.GetFiles(configBackupFolderPath, "configuration*").OrderBy(f => f).ToList();
Not sure what do you mean. Backup for roaming/local configs stored in the different folders in parallel manner.

2021-06-04 08:48 UTC, GeertvanHorrik commented on src/Orchestra.Core/Services/ConfigurationBackupService.cs
> +            var backupConfigurationFiles = _directoryService.GetFiles(configBackupFolderPath, "configuration*").OrderBy(f => f).ToList();
I missed the _appDataService.GetApplicationDataDirectory(applicationDataTarget) backup location. All good now.

2021-06-04 08:52 UTC, GeertvanHorrik requested changes

2021-06-04 08:52 UTC, GeertvanHorrik commented on src/Orchestra.Tests/Orchestra.Core.approved.cs
> +namespace XamlGeneratedNamespace
This should not be committed, this will fail in release mode.

2021-06-04 08:52 UTC, GeertvanHorrik commented on src/Orchestra.Tests/Services/ConfigurationBackupServiceFacts.cs
> +            @"C:\Users\JustAnotherUser\AppData\Roaming\WildGums\Orchestra.Examples.Ribbon.Fluent\testconfiguration.xml",
Remove username, use appdataservice to resolve the path.

2021-06-04 08:52 UTC, GeertvanHorrik commented on src/Orchestra.Tests/Services/ConfigurationBackupServiceFacts.cs
> +            using (fileService.Create(roamingConfigPath))
put using blocks in { }

2021-06-04 08:52 UTC, GeertvanHorrik commented on src/Orchestra.Tests/Services/ConfigurationBackupServiceFacts.cs
> +            var countInRoaming = directoryService.GetFiles(@"C:\Users\JustAnotherUser\AppData\Roaming\Microsoft Corporation\Microsoft.TestHost\backup\config", "configuration*").Count();
Remove username

2021-06-04 09:44 UTC, GeertvanHorrik approved these changes

2021-06-04 09:44 UTC, merged