Allow to set default log cleanup parameters from Log Initialization
WildGums/Orchestra pull request #603
Opened 2022-01-29 12:47 UTC by Averus-a

### Description of Change ###

Purposes of change: we should be able to define how many and how big Log files we want to store

TODO:
- [ ] Add changelog

### Issues Resolved ### 

- fixes #

### API Changes ###

 
None

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

2022-01-30 13:38 UTC, GeertvanHorrik requested changes
The defaults are added, but how can someone override? I think we need properties for this?

2022-01-30 13:38 UTC, GeertvanHorrik commented on src/Orchestra.Core/Helpers/LogHelper.cs
> +        public static int MaxLogFileArchiveDaysDefault = 7;
Please use 14

2022-01-30 13:38 UTC, GeertvanHorrik commented on src/Orchestra.Core/Helpers/LogHelper.cs
> +        public static int MaxLogFileArchiveFilesCountDefault = 10;
Please use 20

2022-01-31 07:06 UTC, Averus-a commented
> The defaults are added, but how can someone override? I think we need properties for this?

![image](https://user-images.githubusercontent.com/14249631/151752016-2e2c0010-e572-4b67-9913-dfc6e248344c.png)
The first option like this
Or we can provide configuration settings

2022-01-31 14:40 UTC, GeertvanHorrik approved these changes

2022-01-31 14:40 UTC, merged