Extend CloseApplicationWatcherBase
WildGums/Orchestra pull request #639
Opened 2022-08-16 16:26 UTC by Averus-a

### Description of Change ###
Reason for changes:
Currently CloseApplicationWatcherBase has two options for adding own action to respond application exit:
- PrepareClosing
- Closing
You can cancel main window Closing event via both methods. Since you don't know for sure what are the watchers registered in the system, you'll force to implement 'undo' in case closing cancellation.
Suggesting add Closed virtual method for actions need to be execute right before closing, when it's known for sure that it is no longer possible to cancel the exit.

### Issues Resolved ### 

- fixes #

### API Changes ###

 
None

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

2022-08-16 16:45 UTC, mkhomutov requested changes

2022-08-16 16:45 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                await ExecuteClosedAsync(ClosedAsync);
the execution of this method will be definitely started, but there is no guarantee that it will be finished before the process will be terminated.

I would recommend to not use keyword `async` with this event handler. And I would use `ExecuteClosedAsync(ClosedAsync).Wait(1000);`
it will wait at least one second when all watchers will execute their actions

2022-08-17 09:56 UTC, GeertvanHorrik commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                await ExecuteClosedAsync(ClosedAsync);
Smart catch. I think in Catel, we do something similar where we always cancel (e.Cancel = true), set an internal flag and re-call the method if we are sure to close. Maybe we can do something similar here instead of calling .Wait (because I am not sure how it will behave when showing a message box).

2022-08-17 10:01 UTC, Averus-a commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                await ExecuteClosedAsync(ClosedAsync);
Changes to sync. Thinking about design, async doesn't really go well with idea of Closed event. Having async here potentially creating misusing scenarios for this watcher.

2022-08-17 10:43 UTC, mkhomutov requested changes

2022-08-17 10:43 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +            catch (TaskCanceledException)
I suppose this type of exception will never be thrown

2022-08-17 19:47 UTC, mkhomutov approved these changes

2022-08-27 20:39 UTC, mkhomutov requested changes
controversial changes. we need to discuss it

2022-08-27 20:39 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +            if (clonedEventArgs.Cancel)
can't find the way how it can be set to true

2022-08-27 20:39 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +            await PerformClosedOperationAsync();
if the whole point of the changes was to run this method after all closing handlers have approved Closing, then you could just do this:
```
if (IsClosingConfirmed)
{
    await PerformClosedOperationAsync();
}
```

2022-08-27 20:39 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                    // Never break on a single watcher
but it could be written into the Log 
or you can store the errors in  some variable and handle it at the end

2022-08-27 20:39 UTC, mkhomutov commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                throw;
why do you throw it if you don't want to handle it in the caller?

2022-08-29 08:46 UTC, GeertvanHorrik commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +        private static bool CanClose = false;
No, closing confirmed means the user allows the app to close. Can Close also means that it as ran all closed methods.

2022-08-29 08:47 UTC, GeertvanHorrik commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +                // We need to run the closing methods, so still need to cancel
Because we are also running ClosedAsync as sync methods.

2022-08-29 08:48 UTC, GeertvanHorrik commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +            await PerformClosedOperationAsync();
Not entirely agree. IsClosingConfirmed == do we allow app to be closed. CanClose == the app can actually be closed since we executed all handlers.

2022-08-29 08:48 UTC, GeertvanHorrik commented on src/Orchestra.Core/ApplicationWatchers/CloseApplicationWatcherBase.cs
> +            // Fully done, now really close
It has been checked before.

2022-08-29 09:25 UTC, GeertvanHorrik approved these changes

2022-08-29 16:29 UTC, mkhomutov approved these changes
thanks, looks good

2022-08-29 17:01 UTC, merged